### PR TITLE
update logic for ignoring duplicate unload requests

### PR DESCRIPTION
**Pull request by nnshah1**
Based on this issue https://github.com/triton-inference-server/server/issues/6359, and the debugging by: [iyLester](https://github.com/iyLester) - a quick change to the logic to identify a duplicate unload request.

Previously the logic would identify every request as 'not first unload', change to identify duplicate unload.

### CODE REVIEW

**Review by kthui — APPROVED** [review]
nice fix!
so the new logic is
```
action:     unload -> load -> unload -> unload
duplicate:    no       no       no       yes
```

**Review by kthui — APPROVED** [review]

**Comment by Joffref** [comment]
Any chance it get merged soon? :+1:

**Comment by nnshah1** [comment]
> Any chance it get merged soon? 👍

The main thing we are waiting on is to add a test case - will see if we can prioritize for 24.06 release.

Let us know if that causes issues for you

**Comment by Joffref** [comment]
> > Any chance it get merged soon? 👍
> 
> The main thing we are waiting on is to add a test case - will see if we can prioritize for 24.06 release.
> 
> Let us know if that causes issues for you

As of today,[ knowing Dragonfly is about to release its repository agent](https://d7y.io/docs/next/operations/integrations/triton-server/), this an ongoing issue that can block us from using it. Is there any workaround that we can use until the release of this patch?

**Comment by nnshah1** [comment]
> > > Any chance it get merged soon? 👍
> > 
> > 
> > The main thing we are waiting on is to add a test case - will see if we can prioritize for 24.06 release.
> > Let us know if that causes issues for you
> 
> As of today,[ knowing Dragonfly is about to release its repository agent](https://d7y.io/docs/next/operations/integrations/triton-server/), this an ongoing issue that can block us from using it. Is there any workaround that we can use until the release of this patch?

I'll bring this up with the team - and see if we can expedite - dragonfly looks really interesting!

**Pull request merged**
