### PR TITLE
Unused variable causing L0_build_variants--build to fail. 

### PR DESCRIPTION
**Pull request by indrajit96**
Unused variable in case of TRITON_ENABLE_METRICS set to OFF causing build failure here
https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/117883872

New Pipeline in progress

https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/pipelines/19741134

### CODE REVIEW

**Comment by yinggeh** [comment]
When you build locally with `-DTRITON_ENABLE_METRICS=OFF`, did you see error or just warning?

**Comment by indrajit96** [comment]
> I wonder when you built locally with `-DTRITON_ENABLE_METRICS=OFF`, did you see error or just warning?

I just checked with `-DTRITON_ENABLE_METRICS=OFF TRITON_ENABLE_METRICS_CPU=OFF TRITON_ENABLE_METRICS_GPU=OFF` the build does error out.
I think I missed running build with metrics OFF after the final refactor which caused this.

**Review by yinggeh — APPROVED** [review]
LGTM! Make sure it passes the CI.

**Review by rmccorm4 — APPROVED** [review]

**Comment by rmccorm4** [comment]
@indrajit96 is this good to go? Did it pass CI? Would be good to fix `L0_build_variants` on nightlies

**Comment by indrajit96** [comment]
> @indrajit96 is this good to go? Did it pass CI? Would be good to fix `L0_build_variants` on nightlies

https://gitlab-master.nvidia.com/dl/dgx/tritonserver/-/jobs/118904982
Was triggered by @KrishnanPrash 
Test passes.
Merging.

**Pull request merged**
